user abc abc;
worker_processes auto;
pid /run/nginx/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 1024; }
http {
  include @MIME_TYPES@;
  default_type application/octet-stream;
  access_log off;
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 65;
  types_hash_max_size 4096;
  client_body_temp_path /run/nginx/body;
  proxy_temp_path /run/nginx/proxy;
  fastcgi_temp_path /run/nginx/fastcgi;
  uwsgi_temp_path /run/nginx/uwsgi;
  scgi_temp_path /run/nginx/scgi;
  include /run/nginx/default.conf;
}
